version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    command: npm run dev
    ports:
      - '24678:24678'
      - '80:3000'
    expose:
      - 3000
    volumes:
      - ./frontend/:/service/frontend
    env_file:
      - ./backend/api/.env
  api:
    build:
      context: .
      dockerfile: ./docker/backend/api/Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - '8000:8000'
    expose:
      - 8000
    volumes:
      - ./backend/api:/service/backend/api
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=shortlink
      - POSTGRES_PASSWORD=tErhP8NV
      - POSTGRES_DB=shortlink
    ports:
      - '5432:5432'
    expose:
      - '5432'

volumes:
  postgres_data:
